version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POOLS_DATABASE_URL=${POOLS_DATABASE_URL}
    restart: unless-stopped 